### ISSUE TITLE
adapter.c - result.visible set to false once UTC time rolls over to 00:00:00 

### ISSUE THREAD

**Issue by xaos11** [jacob-pro/sunrise-sunset-calculator#2]
Expected results:
According to result.set, (currently) result.visible should return false at 01:17:00

Observed results:
I've noticed that result.visible gets set to false as soon as UTC hits 00:00:00. result.visible does get set to true at the expected result.rise time, yet gets set to false just over an hour early (currently).

I took a look at adapter.c and I would guess that the controlling expression needs to be modified (so that result.visible stays true after UTC rolls over) but I'm having a hard _time_ wrapping my head around it

```
        if ((riset <= atTime) && (atTime <= sett)) {
            result->visible = true;
            result->rise = riset;
            result->set = sett;
        }
```

**Comment by jacob-pro** [comment]
Hi, I'm struggling to replicate the issue. Please can you give me the full input you are giving to the `ssc_around_time()` function?

**Comment by jacob-pro** [comment]
For example I have tried with Bristol lat/lon for this evening:

```
At: 28/07/21 20:20       Visible: true           Set: 28/07/21 21:04     Rise: 28/07/21 05:29
At: 28/07/21 20:40       Visible: true           Set: 28/07/21 21:04     Rise: 28/07/21 05:29
At: 28/07/21 21:00       Visible: true           Set: 28/07/21 21:04     Rise: 28/07/21 05:29
At: 28/07/21 21:20       Visible: false          Set: 28/07/21 21:04     Rise: 29/07/21 05:30
At: 28/07/21 21:40       Visible: false          Set: 28/07/21 21:04     Rise: 29/07/21 05:30
At: 28/07/21 22:00       Visible: false          Set: 28/07/21 21:04     Rise: 29/07/21 05:30
At: 28/07/21 22:20       Visible: false          Set: 28/07/21 21:04     Rise: 29/07/21 05:30
At: 28/07/21 22:40       Visible: false          Set: 28/07/21 21:04     Rise: 29/07/21 05:30
At: 28/07/21 23:00       Visible: false          Set: 28/07/21 21:04     Rise: 29/07/21 05:30
At: 28/07/21 23:20       Visible: false          Set: 28/07/21 21:04     Rise: 29/07/21 05:30
At: 28/07/21 23:40       Visible: false          Set: 28/07/21 21:04     Rise: 29/07/21 05:30
At: 29/07/21 00:00       Visible: false          Set: 28/07/21 21:04     Rise: 30/07/21 05:32
At: 29/07/21 00:20       Visible: false          Set: 28/07/21 21:04     Rise: 30/07/21 05:32
At: 29/07/21 00:40       Visible: false          Set: 28/07/21 21:04     Rise: 30/07/21 05:32
At: 29/07/21 01:00       Visible: false          Set: 28/07/21 21:04     Rise: 29/07/21 05:30
At: 29/07/21 01:20       Visible: false          Set: 28/07/21 21:04     Rise: 29/07/21 05:30
At: 29/07/21 01:40       Visible: false          Set: 28/07/21 21:04     Rise: 29/07/21 05:30
At: 29/07/21 02:00       Visible: false          Set: 28/07/21 21:04     Rise: 29/07/21 05:30
At: 29/07/21 02:20       Visible: false          Set: 28/07/21 21:04     Rise: 29/07/21 05:30
At: 29/07/21 02:40       Visible: false          Set: 28/07/21 21:04     Rise: 29/07/21 05:30
At: 29/07/21 03:00       Visible: false          Set: 28/07/21 21:04     Rise: 29/07/21 05:30
At: 29/07/21 03:20       Visible: false          Set: 28/07/21 21:04     Rise: 29/07/21 05:30
At: 29/07/21 03:40       Visible: false          Set: 28/07/21 21:04     Rise: 29/07/21 05:30
At: 29/07/21 04:00       Visible: false          Set: 28/07/21 21:04     Rise: 29/07/21 05:30
At: 29/07/21 04:20       Visible: false          Set: 28/07/21 21:04     Rise: 29/07/21 05:30
At: 29/07/21 04:40       Visible: false          Set: 28/07/21 21:04     Rise: 29/07/21 05:30
At: 29/07/21 05:00       Visible: false          Set: 28/07/21 21:04     Rise: 29/07/21 05:30
At: 29/07/21 05:20       Visible: false          Set: 28/07/21 21:04     Rise: 29/07/21 05:30
At: 29/07/21 05:40       Visible: true           Set: 29/07/21 21:03     Rise: 29/07/21 05:30
At: 29/07/21 06:00       Visible: true           Set: 29/07/21 21:03     Rise: 29/07/21 05:30
At: 29/07/21 06:20       Visible: true           Set: 29/07/21 21:03     Rise: 29/07/21 05:30
```

which gives expected results, so i would need to try with your location and time inputs

**Comment by xaos11** [comment]
Sorry, I should have provided a lat/lon but I was too lazy at the time to obfuscate my exact location that I've been using.
I live in St. Louis so this should do the trick:

38.62727, -90.19789

**Comment by jacob-pro** [comment]
should be fixed in latest commit - i have rewritten that function - can you let me know if it is working for you?

**Comment by xaos11** [comment]
Still going false as soon as UTC time rolls over (checked a second time to be extra sure). I feel like we are closer but I also feel like maybe there's something I'm doing to cause this. 
I am using [timegm.c](https://github.com/junhuanchen/esp32-PCF8563/blob/master/timegm.c) in place of gmtime.c to adapt this to run on an ESP32. Do you think that could possibly have anything to do with my issue?

**Comment by jacob-pro** [comment]
Yeah you're definitely right its still broken sorry

```
At: 28/07/21 18:00       Visible: true           Rise: 28/07/21 05:59    Set: 28/07/21 20:15
At: 28/07/21 19:00       Visible: false          Set: 27/07/21 20:16     Rise: 29/07/21 06:00
```

I will try and fix it tomorrow

**Comment by jacob-pro** [comment]
I think I know what is wrong calcJDofNearestRiseSet() in calculator.c doesn't always calculate the nearest event - i should be able to fix that. tbh the NOAA algorithm is actually horrible now that I think about it.

if i turn off my while loops i get this:
```
At: 28/07/21 18:00       Visible: true           Rise: 28/07/21 05:59    Set: 28/07/21 20:15
At: 28/07/21 19:00       Visible: false          Rise: 29/07/21 06:00    Set: 29/07/21 20:14
```
which doesn't make sense because the nearest set to 19:00 is obviously at 20:15, not a whole 25 hours later!

**Comment by xaos11** [comment]
Good to know it wasn't me! I see that the NOAA calculations are based on equations from Astronomical Algorithms, by Jean Meeus. I wonder what edition they were using as the 2nd edition appears to fix many errors (as well as errata for the 2nd edition). Not that I know what I'm looking at... my brain shuts down!

**Comment by jacob-pro** [comment]
yeah i know how I'm going to fix this - it just might me a couple of days actually.
basically the problem i tried to patch with adapter.c is that when you query for sunrise/sunset for a given day the NOAA algorithm can \*sometimes\* give you an arrangement like: `TimeNow < Sunrise < Sunset`
when really you want `Sunset < TimeNow < Sunset` or `Sunrise < TimeNow < Sunset`
and this problem gets even more weird at extreme longitudes and different timezones

anyway my solution is I'm going to use this solar position algorithm (https://midcdmz.nrel.gov/spa/) to calculate solar elevation.
from that I can then calculate the actual nearest events - like this:
- https://github.com/skyfielders/python-skyfield/blob/aa59e2d4711c3a95804170889f138402edbf4237/skyfield/almanac.py#L216
- https://github.com/skyfielders/python-skyfield/blob/aa59e2d4711c3a95804170889f138402edbf4237/skyfield/searchlib.py#L12

plan is to be ANSI C 89/90 compliant, support all latitudes and longitudes, and accept unix time input and output (which on most platforms is equivalent to time_t)

**Comment by jacob-pro** [comment]
I have done the rewrite - now get these results for St Louis (localtime) (there is a demo app in test/ssc_example.c):
```
At: 28/07/21 19:50       Visible: true           Rise: 28/07/21 05:59    Set: 28/07/21 20:14
At: 28/07/21 20:00       Visible: true           Rise: 28/07/21 05:59    Set: 28/07/21 20:14
At: 28/07/21 20:10       Visible: true           Rise: 28/07/21 05:59    Set: 28/07/21 20:14
At: 28/07/21 20:20       Visible: false          Set: 28/07/21 20:14     Rise: 29/07/21 06:00
At: 28/07/21 20:30       Visible: false          Set: 28/07/21 20:14     Rise: 29/07/21 06:00
At: 28/07/21 20:40       Visible: false          Set: 28/07/21 20:14     Rise: 29/07/21 06:00
```
please can you let me know if this works for you @xaos11?

i don't know anything about the ESP32 - but this library now only uses Unix times, and doesn't depend or use any system time libraries, so there shouldn't be any problems as long as you can convert to/from unix time correctly.

**Comment by xaos11** [comment]
It works!!! I don't know how the heck anyone could have done this in a day... you rock!!!

btw I am using this library to automatically activate "dark mode" for a project I am working on with the M5Stack Core2, running FreeRTOS (ESP-IDF on PlatformIO). Thank you so much!!!

**Comment by jacob-pro** [comment]
awesome! yeah i made this library a while ago for a similar project to change monitor screen brightness, which i'm planning to do some more updates on in future anyway.
i'm going to close this issue, but feel free to open a new one if you find any other bugs.
